[package]
name = "csvjson"
authors = ["Adam Sobotka <vorcigernix@gmail.com>"]
description = "csv to json conversion"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1"
csv = "1.3.0"
serde_json = "1.0.114"
spin-sdk = "2.2.0"

[workspace]
